version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.hugo
    container_name: ftc-web
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - ftc-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ftc-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./api/.env
    restart: unless-stopped
    networks:
      - ftc-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ftc-network:
    driver: bridge
