version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.hugo
    container_name: ftc-web
    expose:
      - "80"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - ftc-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ftc-api
    expose:
      - "3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - BASE_URL=${BASE_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    restart: unless-stopped
    networks:
      - ftc-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ftc-cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - ftc-network
    depends_on:
      - web

networks:
  ftc-network:
    driver: bridge
