baseURL = 'https://your-domain.com/'
languageCode = 'en-us'
title = 'FIRST Tech Challenge Team'
theme = 'PaperMod'

[params]
  description = "Our FIRST Tech Challenge team website"
  author = "FTC Team"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[params.homeInfoParams]
  Title = "Welcome to Our FTC Team"
  Content = "Follow our journey in robotics competition"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "Store"
  url = "/store/"
  weight = 3

[[menu.main]]
  name = "Donate"
  url = "/donate/"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]
