baseURL = 'https://roosterbots.designbuildautomate.io'
languageCode = 'en-us'
title = 'RoosterBots'
theme = 'PaperMod'

[params]
  description = "RoosterBots - FIRST Tech Challenge Team from West Virginia"
  author = "RoosterBots FTC Team"
  images = ["/images/logo.png"]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[params.homeInfoParams]
  Title = "Welcome to RoosterBots"
  Content = "West Virginia's Premier FIRST Tech Challenge Team - Building robots, building futures."

[params.profileMode]
  enabled = false

[params.label]
  text = "RoosterBots"
  icon = "/images/logo.png"
  iconHeight = 35

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "Store"
  url = "/store/"
  weight = 3

[[menu.main]]
  name = "Donate"
  url = "/donate/"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]
