# Change this to https://roosterbots.org when ready for production
baseURL = 'https://roosterbots.designbuildautomate.io'
languageCode = 'en-us'
title = 'RoosterBots FTC #31669'
theme = 'PaperMod'

[params]
  description = "RoosterBots FTC Team #31669 - Lost River Valley, West Virginia - Chesapeake Region"
  author = "RoosterBots FTC Team #31669"
  images = ["/images/logo.png"]
  keywords = ["FTC", "FIRST Tech Challenge", "Robotics", "West Virginia", "Team 31669", "RoosterBots", "Chesapeake"]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[params.homeInfoParams]
  Title = "RoosterBots FTC #31669"
  Content = "Lost River Valley, West Virginia | Chesapeake Region | 2025-2026 Season"

[params.profileMode]
  enabled = false

[params.label]
  text = "RoosterBots"
  icon = "/images/logo.png"
  iconHeight = 35

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "Store"
  url = "/store/"
  weight = 3

[[menu.main]]
  name = "Donate"
  url = "/donate/"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]
